package cps1

import (
	"encoding/json"
	"net/url"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// goldenFile is the shared cross-language fixture. Every implementation of the
// signing contract — this package, the Python SDK, and every published
// SDK — must reproduce expected_signature exactly (07§4.1, adjudication D4).
const goldenFile = "../../proto-hub/testdata/cps1-golden-vectors.json"

type goldenVector struct {
	Name                  string            `json:"name"`
	Description           string            `json:"description"`
	Method                string            `json:"method"`
	Host                  string            `json:"host"`
	Path                  string            `json:"path"`
	Query                 map[string]string `json:"query"`
	Headers               map[string]string `json:"headers"`
	Body                  string            `json:"body"`
	AK                    string            `json:"ak"`
	SK                    string            `json:"sk"`
	Region                string            `json:"region"`
	Service               string            `json:"service"`
	Date                  string            `json:"date"`
	ExpectedAuthorization string            `json:"expected_authorization"`
	ExpectedSignature     string            `json:"expected_signature"`
}

type goldenFixture struct {
	Algorithm string         `json:"algorithm"`
	Vectors   []goldenVector `json:"vectors"`
}

// TestGoldenVectorsFile pins the wire contract. If this fails, either the
// algorithm changed (a breaking change requiring a new SDK major version) or
// the fixture was regenerated by accident.
func TestGoldenVectorsFile(t *testing.T) {
	data, err := os.ReadFile(filepath.FromSlash(goldenFile))
	if err != nil {
		t.Skipf("golden fixture not present (%v); run gen-vectors to create it", err)
	}
	var fx goldenFixture
	if err := json.Unmarshal(data, &fx); err != nil {
		t.Fatalf("parse golden fixture: %v", err)
	}
	if fx.Algorithm != Algorithm {
		t.Fatalf("fixture algorithm = %q, want %q", fx.Algorithm, Algorithm)
	}
	if len(fx.Vectors) == 0 {
		t.Fatal("fixture contains no vectors")
	}

	for _, v := range fx.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			at, err := time.Parse(time.RFC3339, v.Date)
			if err != nil {
				t.Fatalf("parse date: %v", err)
			}
			q := url.Values{}
			for k, val := range v.Query {
				q.Set(k, val)
			}

			signed, err := Sign(Request{
				Method:  v.Method,
				Host:    v.Host,
				Path:    v.Path,
				Query:   q,
				Headers: v.Headers,
				Body:    []byte(v.Body),
			}, Credentials{AK: v.AK, SK: v.SK}, v.Region, v.Service, at)
			if err != nil {
				t.Fatalf("Sign: %v", err)
			}

			if signed.Authorization != v.ExpectedAuthorization {
				t.Errorf("Authorization drift:\n got  %s\n want %s",
					signed.Authorization, v.ExpectedAuthorization)
			}

			// The signature must also verify through the verification path,
			// not just match the recorded string.
			hdrs := make(map[string]string, len(v.Headers)+1)
			for k, val := range v.Headers {
				hdrs[k] = val
			}
			hdrs["Authorization"] = signed.Authorization
			if err := Verify(Request{
				Method:  v.Method,
				Host:    v.Host,
				Path:    v.Path,
				Query:   q,
				Headers: hdrs,
				Body:    []byte(v.Body),
			}, Credentials{AK: v.AK, SK: v.SK}, v.Region, v.Service, at); err != nil {
				t.Errorf("Verify on golden vector failed: %v", err)
			}
		})
	}
}
