"""Cross-language CPS1 golden-vector regression (03§9.4 rule ⑤).

Every implementation of the signing contract — Go ``pkg-go/cps1``, this Python
SDK, and all published SDKs — must reproduce ``expected_signature`` exactly
(07-security.md §4.1, adjudication D4). This test pins the Python implementation
to the shared fixture generated by ``services/svc-iam/cmd/gen-vectors``; if it
fails, the Python signer drifted from the Go contract.

Run: pytest sdk/python/tests/  (from repo root, or with PYTHONPATH=sdk/python)
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from cloudsdk import (
    ALGORITHM,
    Credentials,
    sign,
    product_api_host,
    service_namespace,
)

# The fixture lives at a repo-relative path; resolve from this file so the test
# works regardless of the CWD pytest is invoked from.
HERE = Path(__file__).resolve().parent
GOLDEN = HERE.parent.parent.parent / "proto-hub" / "testdata" / "cps1-golden-vectors.json"


def _load_vectors() -> list[dict]:
    if not GOLDEN.exists():
        pytest.skip("golden fixture not present: %s" % GOLDEN)
    data = json.loads(GOLDEN.read_text(encoding="utf-8"))
    assert data["algorithm"] == ALGORITHM
    vectors = data["vectors"]
    assert vectors, "fixture contains no vectors"
    return vectors


def _date_value(iso8601: str) -> str:
    """Convert '2026-08-04T09:30:00Z' -> '20260804T093000Z' (x-cps-date form)."""
    # The fixture stores date as RFC3339; cps1 signs the compact form.
    d = iso8601.replace("-", "").replace(":", "")
    return d  # already ends in Z -> 20260804T093000Z


@pytest.mark.parametrize("v", _load_vectors(), ids=lambda v: v["name"])
def test_python_signer_matches_golden_vectors(v: dict) -> None:
    date_value = _date_value(v["date"])
    creds = Credentials(ak=v["ak"], sk=v["sk"], security_token="")
    # The fixture's headers already carry host/date/content-sha/nonce (+ token);
    # feed them in so the canonical set matches the Go run exactly.
    headers = dict(v["headers"])

    signed = sign(
        method=v["method"],
        host=v["host"],
        path=v["path"],
        query=v["query"],
        headers=headers,
        body=v["body"].encode("utf-8"),
        creds=creds,
        region=v["region"],
        service=v["service"],
        date_value=date_value,
    )

    assert signed.signature == v["expected_signature"], (
        "signature drift for %s:\n got  %s\n want %s"
        % (v["name"], signed.signature, v["expected_signature"])
    )
    assert signed.authorization == v["expected_authorization"], (
        "authorization drift for %s:\n got  %s\n want %s"
        % (v["name"], signed.authorization, v["expected_authorization"])
    )
    # SignedHeaders must list host + every x-cps-* present.
    for mandatory in ("host", "x-cps-content-sha256", "x-cps-date", "x-cps-nonce"):
        assert mandatory in signed.signed_headers


def test_service_namespace_derivation() -> None:
    cases = {
        "scecs": "ecs",
        "scoss": "oss",
        "scvpc": "vpc",
        "scrds": "rds",
        "scmon": "mon",
        "sceip": "eip",
    }
    for product, want in cases.items():
        assert service_namespace(product) == want


def test_product_api_host_routing_subdomain() -> None:
    assert product_api_host("scecs") == "scecs.api.starcloud.cn"


def test_sign_rejects_missing_credentials() -> None:
    with pytest.raises(ValueError):
        sign(
            method="GET",
            host="scecs.api.starcloud.cn",
            path="/",
            query={},
            headers={
                "host": "scecs.api.starcloud.cn",
                "x-cps-date": "20260804T093000Z",
                "x-cps-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                "x-cps-nonce": "n",
            },
            body=b"",
            creds=Credentials(ak="", sk=""),
            region="cn-north-1",
            service="ecs",
            date_value="20260804T093000Z",
        )


def test_parse_error_decodes_platform_envelope() -> None:
    from cloudsdk import _parse_error, ApiError

    body = b'{"RequestId":"r1","Code":"Quota.Exceeded","Message":"quota exceeded"}'
    err = _parse_error(body, 403)
    assert isinstance(err, ApiError)
    assert err.code == "Quota.Exceeded"
    assert err.http_status == 403
    assert err.message == "quota exceeded"


def test_parse_error_falls_back_on_unstructured_body() -> None:
    from cloudsdk import _parse_error, ApiError

    err = _parse_error(b"<html>bad gateway</html>", 502)
    assert isinstance(err, ApiError)
    assert err.code == "Common.InternalError"
    assert err.http_status == 502


if __name__ == "__main__":
    # Allow `python test_golden_vectors.py` as a fallback without pytest.
    for v in _load_vectors():
        test_python_signer_matches_golden_vectors(v)
    print("all golden vectors pass")
